# Generated by Django 3.0.8 on 2020-09-12 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0003_auto_20200912_0603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AlterModelOptions(
            name='tipomovimiento',
            options={'verbose_name': 'Tipo de Movimiento', 'verbose_name_plural': 'TiposMovimientos'},
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='nombre',
        ),
    ]
