# Generated by Django 3.0.8 on 2020-09-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0004_auto_20200912_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='numeroComprobante',
            field=models.CharField(default=1, max_length=100, verbose_name='Observaciones'),
            preserve_default=False,
        ),
    ]
