# Generated by Django 3.0.8 on 2020-09-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0005_movimiento_numerocomprobante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lugaralmacen',
            options={'verbose_name': 'LugardeAlamcen', 'verbose_name_plural': 'Almacenes'},
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='numeroComprobante',
            field=models.CharField(max_length=100, verbose_name='Numero de comprobante'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones'),
        ),
    ]
