# Generated by Django 3.0.8 on 2020-09-12 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0008_movimiento_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoImpuesto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Impuesto')),
            ],
            options={
                'verbose_name': 'Tipo de Impuesto',
                'verbose_name_plural': 'Impuestos',
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='impuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Stock.TipoImpuesto'),
        ),
    ]
