# Generated by Django 3.0.8 on 2020-09-12 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0009_auto_20200912_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoimpuesto',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
