# Generated by Django 3.0.8 on 2020-09-12 19:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0010_tipoimpuesto_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ganancias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Impuesto')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Tipo de Impuesto',
                'verbose_name_plural': 'Impuestos',
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='ganancia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Stock.Ganancias'),
        ),
    ]
