# Generated by Django 3.0.8 on 2020-10-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('turno', models.CharField(max_length=50, verbose_name='Turno')),
                ('borrado', models.BooleanField(default=False, verbose_name='borrado')),
            ],
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='turno',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='turno',
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Movistar', 'Movistar'), ('Otro', 'Otro'), ('Personal', 'Personal'), ('Claro', 'Claro'), ('Tuenti', 'Tuenti')], max_length=50, null=True, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='turno',
            field=models.ManyToManyField(blank=True, to='Personas.Turno'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='turno',
            field=models.ManyToManyField(blank=True, to='Personas.Turno'),
        ),
    ]
