# Generated by Django 3.0.8 on 2020-08-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Movistar', 'Movistar'), ('Tuenti', 'Tuenti'), ('Claro', 'Claro'), ('Otro', 'Otro'), ('Personal', 'Personal')], max_length=50, null=True, verbose_name='Empresa'),
        ),
    ]
