# Generated by Django 3.0.8 on 2020-08-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='turno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Turno de trabajo del tecnico'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Tuenti', 'Tuenti'), ('Movistar', 'Movistar'), ('Claro', 'Claro'), ('Otro', 'Otro'), ('Personal', 'Personal')], max_length=50, null=True, verbose_name='Empresa'),
        ),
    ]
