# Generated by Django 3.0.8 on 2020-09-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0004_auto_20200907_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': (('es_cliente', 'es cliente'), ('es_pre_cliente', 'es pre cliente')), 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'permissions': (('es_Empleado', 'es Empleado'), ('es_pre_Empleado', 'es pre Empleado')), 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='tecnico',
            options={'permissions': (('es_Tecnico', 'es Tecnico'), ('es_pre_Tecnico', 'es pre Tecnico')), 'verbose_name': 'Tecnico', 'verbose_name_plural': 'Tecnicos'},
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Claro', 'Claro'), ('Otro', 'Otro'), ('Tuenti', 'Tuenti'), ('Movistar', 'Movistar')], max_length=50, null=True, verbose_name='Empresa'),
        ),
    ]
