# Generated by Django 3.0.8 on 2020-08-15 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0005_auto_20200814_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Movistar', 'Movistar'), ('Claro', 'Claro'), ('Tuenti', 'Tuenti'), ('Otro', 'Otro')], max_length=50, null=True, verbose_name='Empresa'),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('dni', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del usuario')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellido del usuario')),
                ('fechaNac', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(max_length=50, verbose_name='Sexo de la persona')),
                ('correoElectronico', models.EmailField(max_length=254, verbose_name='Correo electronico del usuario')),
                ('estado', models.BooleanField(default=False, verbose_name='Usuario activo/inactivo')),
                ('turno', models.CharField(max_length=100, verbose_name='Turno de trabajo del Empleado')),
                ('puesto', models.CharField(max_length=100, verbose_name='Puesto de trabajo del Empleado')),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Personas.Domicilio')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Personas.Rol')),
                ('telefono', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Personas.Telefono')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
