# Generated by Django 3.0.8 on 2020-09-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0007_auto_20200908_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Claro', 'Claro'), ('Tuenti', 'Tuenti'), ('Personal', 'Personal'), ('Movistar', 'Movistar'), ('Otro', 'Otro')], max_length=50, null=True, verbose_name='Empresa'),
        ),
    ]
