# Generated by Django 3.0.8 on 2020-08-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0008_auto_20200817_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Claro', 'Claro'), ('Movistar', 'Movistar'), ('Otro', 'Otro'), ('Tuenti', 'Tuenti'), ('Personal', 'Personal')], max_length=50, null=True, verbose_name='Empresa'),
        ),
    ]
