# Generated by Django 3.0.8 on 2020-08-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0010_auto_20200817_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Otro', 'Otro'), ('Tuenti', 'Tuenti'), ('Personal', 'Personal'), ('Movistar', 'Movistar'), ('Claro', 'Claro')], max_length=50, null=True, verbose_name='Empresa'),
        ),
    ]
