# Generated by Django 3.0.8 on 2020-09-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0017_auto_20200912_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Otro', 'Otro'), ('Movistar', 'Movistar'), ('Personal', 'Personal'), ('Claro', 'Claro'), ('Tuenti', 'Tuenti')], max_length=50, null=True, verbose_name='Empresa'),
        ),
    ]
