# Generated by Django 3.0.8 on 2020-08-15 00:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Personas', '0005_auto_20200814_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('codEquipo', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de Servicio')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo del equipo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Personas.Cliente')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['cliente'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Estado del equipo')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estado',
            },
        ),
        migrations.CreateModel(
            name='Estado_Repuesto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Estado del equipo')),
            ],
            options={
                'verbose_name': 'Estado_Repuesto',
                'verbose_name_plural': 'Estado_Repuesto',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Marca del equipo')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marca',
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del tipo de equipo')),
            ],
            options={
                'verbose_name': 'TipoEquipo',
                'verbose_name_plural': 'TipoEquipo',
            },
        ),
        migrations.CreateModel(
            name='Servicio_Tecnico',
            fields=[
                ('codServicio', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de Servicio')),
                ('fechaIngreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('problema', models.CharField(max_length=120, verbose_name='Descripcion del problema')),
                ('contraseña', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contraseña del equipo')),
                ('cargador', models.BooleanField(default=False)),
                ('fechaEntrega', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('trabajosRealizados', models.CharField(blank=True, max_length=120, null=True, verbose_name='Trabajos realizados sobre el equipo')),
                ('ubicacion', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ubicacion o Estante en el que se encuentra')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Servicios.Equipo')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Servicios.Estado')),
            ],
            options={
                'verbose_name': 'Servicio_Tecnico',
                'verbose_name_plural': 'Servicios_Tecnicos',
                'ordering': ['codServicio'],
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('codRepuesto', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Codigo de Repuesto')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Repuesto')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion del Repuesto')),
                ('stock', models.PositiveIntegerField()),
                ('entrega', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Servicios.Estado_Repuesto')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Servicios.Servicio_Tecnico')),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Servicios.Marca'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipoEquipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Servicios.TipoEquipo'),
        ),
    ]
