# Generated by Django 3.0.8 on 2020-07-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Repuesto'),
        ),
    ]
