# Generated by Django 3.0.8 on 2020-08-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Disco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disco', models.CharField(max_length=100, verbose_name='Tipo de disco')),
                ('capacidad', models.CharField(max_length=100, verbose_name='Capacidad de disco')),
            ],
            options={
                'verbose_name': 'Tipo_Disco',
                'verbose_name_plural': 'Tipos_de_Disco',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Memoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('memoria', models.CharField(max_length=100, verbose_name='Tipo de memoria')),
                ('capacidad', models.CharField(max_length=100, verbose_name='Capacidad de memoria')),
            ],
            options={
                'verbose_name': 'Tipo_Memoria',
                'verbose_name_plural': 'Tipos_de_Memoria',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Sistema_Operativo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sistemaOperativo', models.CharField(max_length=100, verbose_name='Tipo de Sistema Operativo')),
                ('version', models.CharField(max_length=100, verbose_name='Version del Sistema Operativo')),
            ],
            options={
                'verbose_name': 'Tipo_Sistema_Operativo',
                'verbose_name_plural': 'Tipos_Sistemas_Operativos',
            },
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='codEquipo',
            new_name='id',
        ),
    ]
