# Generated by Django 3.0.8 on 2020-09-08 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0002_capacidaddisco_capacidadmemoria_tipodisco_tipomemoria_tiposo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio_tecnico',
            name='capacidadDisco',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='Servicios.CapacidadDisco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio_tecnico',
            name='capacidadMemoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='Servicios.CapacidadMemoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio_tecnico',
            name='disco',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='Servicios.TipoDisco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio_tecnico',
            name='memoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='Servicios.TipoMemoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio_tecnico',
            name='sistemaOperativo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='Servicios.TipoSO'),
            preserve_default=False,
        ),
    ]
