# Generated by Django 3.0.8 on 2020-08-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0004_auto_20200817_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='url1',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Referencias para resolver un problema'),
        ),
        migrations.AddField(
            model_name='blog',
            name='url2',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Referencias para resolver un problema'),
        ),
        migrations.AddField(
            model_name='blog',
            name='url3',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Referencias para resolver un problema'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='descripcion del blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='imagen',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
