# Generated by Django 3.0.8 on 2020-09-08 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0004_auto_20200907_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposo',
            options={'verbose_name': 'TipoSO', 'verbose_name_plural': 'TipoSO'},
        ),
        migrations.AlterField(
            model_name='equipo',
            name='capacidadDisco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Servicios.CapacidadDisco'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='capacidadMemoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Servicios.CapacidadMemoria'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='disco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Servicios.TipoDisco'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='memoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Servicios.TipoMemoria'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='sistemaOperativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Servicios.TipoSO'),
        ),
    ]
