# Generated by Django 3.0.8 on 2020-09-08 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0005_auto_20200908_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio_tecnico',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Servicios.Equipo'),
        ),
        migrations.AlterField(
            model_name='servicio_tecnico',
            name='fechaIngreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='servicio_tecnico',
            name='problema',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Descripcion del problema'),
        ),
    ]
