# Generated by Django 3.0.8 on 2020-09-11 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0007_auto_20200908_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Accesorio')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion Accesorio')),
            ],
            options={
                'verbose_name': 'Accesorio',
                'verbose_name_plural': 'Accesorio',
            },
        ),
        migrations.RemoveField(
            model_name='servicio_tecnico',
            name='cargador',
        ),
        migrations.AddField(
            model_name='servicio_tecnico',
            name='accesorio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='Servicios.Accesorio'),
            preserve_default=False,
        ),
    ]
