# Generated by Django 3.0.8 on 2020-09-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0008_auto_20200911_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesorio',
            name='descripcion',
        ),
    ]
