# Generated by Django 3.0.8 on 2020-09-12 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0017_auto_20200912_1424'),
        ('Servicios', '0009_remove_accesorio_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio_tecnico',
            name='tecnico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Personas.Tecnico'),
            preserve_default=False,
        ),
    ]
