# Generated by Django 3.0.8 on 2020-09-12 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0018_auto_20200912_1432'),
        ('Servicios', '0010_servicio_tecnico_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio_tecnico',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Personas.Tecnico'),
        ),
    ]
