# Generated by Django 3.0.8 on 2020-10-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id_configuracion', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('logo', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
